/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, ImageProps, TextProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type PoolListCom1440pxOverridesProps = {
    PoolListCom1440px?: PrimitiveOverrideProps<FlexProps>;
    Networks39313311?: PrimitiveOverrideProps<FlexProps>;
    "Networks List"?: PrimitiveOverrideProps<TextProps>;
    "NetWork List39563027"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 1939313310"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39313309"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2039563282"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563283"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 21"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563285"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 22"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563287"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 23"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563289"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 24"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563291"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 25"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563293"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 26"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563295"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 27"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563297"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 28"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563299"?: PrimitiveOverrideProps<ImageProps>;
    Networks39563029?: PrimitiveOverrideProps<FlexProps>;
    "Dex List"?: PrimitiveOverrideProps<TextProps>;
    "NetWork List39563031"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 29"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563301"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 30"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563303"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 31"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563305"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 32"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563307"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 33"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563309"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 34"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563311"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 35"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563313"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 36"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563315"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 3739563316"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563317"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 3839563318"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39563319"?: PrimitiveOverrideProps<ImageProps>;
    PoolItem?: PrimitiveOverrideProps<FlexProps>;
    Top?: PrimitiveOverrideProps<FlexProps>;
    "Frame 3739412765"?: PrimitiveOverrideProps<FlexProps>;
    "LP List"?: PrimitiveOverrideProps<TextProps>;
    "Frame 13"?: PrimitiveOverrideProps<FlexProps>;
    WALLET?: PrimitiveOverrideProps<TextProps>;
    "Frame 3839573866"?: PrimitiveOverrideProps<FlexProps>;
    DEPOSITED?: PrimitiveOverrideProps<TextProps>;
    "Frame 39"?: PrimitiveOverrideProps<FlexProps>;
    APY?: PrimitiveOverrideProps<TextProps>;
    "Frame 14"?: PrimitiveOverrideProps<FlexProps>;
    TVL?: PrimitiveOverrideProps<TextProps>;
    "Frame 40"?: PrimitiveOverrideProps<FlexProps>;
    "DAILY RATE"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1539313304"?: PrimitiveOverrideProps<FlexProps>;
    Action?: PrimitiveOverrideProps<TextProps>;
    List?: PrimitiveOverrideProps<FlexProps>;
    "Frame 11"?: PrimitiveOverrideProps<FlexProps>;
    PoolImg?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:AYOloXgqjzo39313162"?: PrimitiveOverrideProps<ImageProps>;
    "unsplash:em1OiomfG3g39313163"?: PrimitiveOverrideProps<ImageProps>;
    LogoTitle?: PrimitiveOverrideProps<FlexProps>;
    "Overnight Pulse Act ll"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 9"?: PrimitiveOverrideProps<FlexProps>;
    VELOCIMETER?: PrimitiveOverrideProps<TextProps>;
    "Frame 8"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:AYOloXgqjzo39313160"?: PrimitiveOverrideProps<ImageProps>;
    "STADER BOOST"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1539313290"?: PrimitiveOverrideProps<FlexProps>;
    "039313291"?: PrimitiveOverrideProps<TextProps>;
    "Frame 18"?: PrimitiveOverrideProps<FlexProps>;
    "039573871"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1939573872"?: PrimitiveOverrideProps<FlexProps>;
    "99.99%"?: PrimitiveOverrideProps<TextProps>;
    "Frame 16"?: PrimitiveOverrideProps<FlexProps>;
    "$999,99939313294"?: PrimitiveOverrideProps<TextProps>;
    "Frame 2039574040"?: PrimitiveOverrideProps<FlexProps>;
    "$999,99939574041"?: PrimitiveOverrideProps<TextProps>;
    "Frame 17"?: PrimitiveOverrideProps<FlexProps>;
    "Add Liquidity"?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type PoolListCom1440pxProps = React.PropsWithChildren<Partial<FlexProps> & {
    overrides?: PoolListCom1440pxOverridesProps | undefined | null;
}>;
export default function PoolListCom1440px(props: PoolListCom1440pxProps): React.ReactElement;
