/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 moon.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Moon(props) {
  const { nodes, materials } = useGLTF("./gltf/moon.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mars.geometry}
        material={materials.Mars}
        scale={4.16}
      />
    </group>
  );
}

useGLTF.preload("./gltf/moon.glb");
