/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 cupcakeOne.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CupcakeOne(props) {
  const { nodes, materials } = useGLTF("./gltf/cupcakeOne.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Star.geometry}
        material={materials["Material.004"]}
        position={[-0.05, 1.42, 0.05]}
        scale={[1.09, 0.52, 1.09]}
      >
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.006"]}
          position={[0.73, -0.68, -0.17]}
          rotation={[-2.75, -1.03, -0.63]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_3.geometry}
          material={materials["Material.006"]}
          position={[0.66, -0.69, -0.06]}
          rotation={[-2.82, -0.87, -0.7]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_4.geometry}
          material={materials["Material.006"]}
          position={[0.64, -0.85, -0.37]}
          rotation={[-0.14, -0.52, 2.2]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_5.geometry}
          material={materials["Material.006"]}
          position={[0.07, -0.68, -0.74]}
          rotation={[-0.29, -0.4, 2.14]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_6.geometry}
          material={materials["Material.006"]}
          position={[-0.15, -0.69, -0.67]}
          rotation={[0.38, 0.56, -1.08]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_7.geometry}
          material={materials["Material.006"]}
          position={[-0.74, -0.85, -0.07]}
          rotation={[-2.87, 0.98, -1.1]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_8.geometry}
          material={materials["Material.006"]}
          position={[-0.13, -0.68, 0.59]}
          rotation={[2.95, -0.08, 2.24]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_9.geometry}
          material={materials["Material.006"]}
          position={[0.5, -0.96, 0.27]}
          rotation={[-1.82, -0.81, 0.13]}
          scale={[0.04, 0.05, 0.04]}
        />
        <mesh
          geometry={nodes.Cube001_10.geometry}
          material={materials["Material.006"]}
          position={[0.44, -0.98, -0.06]}
          rotation={[-1.81, -0.48, 0.02]}
          scale={[0.03, 0.04, 0.04]}
        />
        <mesh
          geometry={nodes.Cube001_11.geometry}
          material={materials["Material.006"]}
          position={[-0.41, -0.97, 0.23]}
          rotation={[-2.29, 0.23, -1.47]}
          scale={[0.03, 0.05, 0.04]}
        />
        <mesh
          geometry={nodes.Cube001_12.geometry}
          material={materials["Material.006"]}
          position={[0.04, -0.99, 0.38]}
          rotation={[-1.85, -0.19, -0.6]}
          scale={[0.02, 0.04, 0.05]}
        />
        <mesh
          geometry={nodes.Cube001_13.geometry}
          material={materials["Material.006"]}
          position={[0.19, -0.98, 0.4]}
          rotation={[-2.1, -0.17, -0.96]}
          scale={[0.03, 0.04, 0.04]}
        />
        <mesh
          geometry={nodes.Cube001_14.geometry}
          material={materials["Material.006"]}
          position={[-0.26, 0.76, -0.19]}
          rotation={[0.04, 0.35, -0.9]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_15.geometry}
          material={materials["Material.006"]}
          position={[-0.2, 0.75, -0.21]}
          rotation={[0.11, 0.32, -0.91]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_16.geometry}
          material={materials["Material.006"]}
          position={[-0.3, 0.55, -0.21]}
          rotation={[0.52, 0.64, -1.21]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_17.geometry}
          material={materials["Material.006"]}
          position={[-0.34, 0, 0.61]}
          rotation={[-2.56, 0.64, -1.26]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_18.geometry}
          material={materials["Material.006"]}
          position={[-0.38, -0.02, 0.48]}
          rotation={[-2.6, 0.76, -1.26]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_19.geometry}
          material={materials["Material.006"]}
          position={[-0.34, -0.19, 0.44]}
          rotation={[-3.04, 0.63, -0.94]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_20.geometry}
          material={materials["Material.006"]}
          position={[0.06, -0.34, 0.72]}
          rotation={[-2.77, 0.27, -1.01]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_21.geometry}
          material={materials["Material.006"]}
          position={[0, 0.75, -0.36]}
          rotation={[0.64, 0.38, -1.25]}
          scale={[0.04, 0.05, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_22.geometry}
          material={materials["Material.006"]}
          position={[-0.69, 0.15, -0.24]}
          rotation={[0.54, 0.93, -1.3]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_23.geometry}
          material={materials["Material.006"]}
          position={[-0.57, -0.01, 0.12]}
          rotation={[2.64, 0.65, 2.46]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_24.geometry}
          material={materials["Material.006"]}
          position={[0.02, 0.96, -0.11]}
          rotation={[0.85, -0.42, -0.68]}
          scale={[0.03, 0.05, 0.04]}
        />
        <mesh
          geometry={nodes.Cube001_25.geometry}
          material={materials["Material.006"]}
          position={[0.14, 0.89, -0.13]}
          rotation={[0.8, -0.75, -0.45]}
          scale={[0.04, 0.05, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_26.geometry}
          material={materials["Material.006"]}
          position={[0.08, 0.76, -0.35]}
          rotation={[-0.05, -0.67, 2.23]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_27.geometry}
          material={materials["Material.006"]}
          position={[-0.28, 0.33, -0.46]}
          rotation={[-0.02, 0.07, 2.26]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_28.geometry}
          material={materials["Material.006"]}
          position={[-0.26, 0.15, -0.46]}
          rotation={[0.11, 0.39, -0.92]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_29.geometry}
          material={materials["Material.006"]}
          position={[-0.69, 0, -0.13]}
          rotation={[-0.49, 0.65, 2.46]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_30.geometry}
          material={materials["Material.006"]}
          position={[-0.58, -0.02, -0.21]}
          rotation={[-0.36, 0.6, 2.39]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_31.geometry}
          material={materials["Material.006"]}
          position={[-0.56, -0.52, 0.13]}
          rotation={[-0.07, 1.25, 2.28]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_32.geometry}
          material={materials["Material.006"]}
          position={[-0.67, -0.34, 0.28]}
          rotation={[-0.68, 1.08, 2.74]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_33.geometry}
          material={materials["Material.006"]}
          position={[0.31, 0.75, -0.15]}
          rotation={[0.6, -0.46, -0.74]}
          scale={[0.04, 0.05, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_34.geometry}
          material={materials["Material.006"]}
          position={[-0.41, -0.19, -0.63]}
          rotation={[0.34, 0.58, -1.07]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_35.geometry}
          material={materials["Material.006"]}
          position={[0.32, 0.76, -0.06]}
          rotation={[3.02, -0.76, 2.18]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_36.geometry}
          material={materials["Material.006"]}
          position={[0.29, 0.75, -0.02]}
          rotation={[2.94, -0.71, 2.14]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_37.geometry}
          material={materials["Material.006"]}
          position={[0.02, -0.19, -0.56]}
          rotation={[-0.06, -0.13, 2.25]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_38.geometry}
          material={materials["Material.006"]}
          position={[-0.08, 0, -0.7]}
          rotation={[-0.44, -0.24, 2.1]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_39.geometry}
          material={materials["Material.006"]}
          position={[-0.35, -0.36, -0.55]}
          rotation={[-0.32, 0.07, 2.24]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_40.geometry}
          material={materials["Material.006"]}
          position={[0.47, -0.19, -0.58]}
          rotation={[0.25, -0.4, -0.83]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_41.geometry}
          material={materials["Material.006"]}
          position={[0.13, 0.76, 0.23]}
          rotation={[3.04, 0.28, 2.28]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_42.geometry}
          material={materials["Material.006"]}
          position={[0.48, 0.33, 0.2]}
          rotation={[3.14, -0.49, -0.89]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_43.geometry}
          material={materials["Material.006"]}
          position={[0.47, 0.15, 0.21]}
          rotation={[2.94, -0.82, 2.12]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_44.geometry}
          material={materials["Material.006"]}
          position={[0.21, 0.35, 0.45]}
          rotation={[2.47, -0.56, 1.81]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_45.geometry}
          material={materials["Material.006"]}
          position={[0.68, -0.36, -0.04]}
          rotation={[0.53, -0.68, -0.65]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_46.geometry}
          material={materials["Material.006"]}
          position={[-0.26, 0.55, 0.2]}
          rotation={[2.66, 0.7, 2.48]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          geometry={nodes.Cube001_47.geometry}
          material={materials["Material.006"]}
          position={[-0.21, 0.76, 0.17]}
          rotation={[3.08, 1.19, 2.28]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_48.geometry}
          material={materials["Material.006"]}
          position={[-0.04, 0.33, 0.5]}
          rotation={[-3.11, 0.51, -0.9]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_49.geometry}
          material={materials["Material.006"]}
          position={[0.53, -0.52, 0.22]}
          rotation={[-3.09, -0.79, -0.86]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_50.geometry}
          material={materials["Material.006"]}
          position={[0.46, -0.64, 0.59]}
          rotation={[2.66, -0.77, 1.93]}
          scale={[0.04, 0.06, 0.02]}
        />
        <mesh
          geometry={nodes.Cube001_51.geometry}
          material={materials["Material.006"]}
          position={[-0.23, 0.04, 0.61]}
          rotation={[2.57, -0.2, 2.03]}
          scale={[0.04, 0.05, 0.03]}
        />
      </mesh>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials["Material.006"]}
        position={[-0.05, 0.71, 0]}
        scale={[0.81, 0.53, 0.81]}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Material.002"]}
        position={[-0.04, 0.48, -0.01]}
        scale={[-0.87, -0.63, -0.87]}
      />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials["Material.007"]}
        position={[-0.28, 0.76, 0.73]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials["Material.007"]}
        position={[0.15, 0.75, 0.76]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials["Material.003"]}
        position={[0.38, 0.63, 0.72]}
        rotation={[0.12, 0.34, 0.15]}
        scale={[0.09, 0.09, 0.06]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[-0.53, 1, 0]}
        rotation={[-0.09, -0.17, -0.1]}
        scale={[0.09, 0.09, 0.06]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.006"]}
        position={[-0.63, 1.65, 0.31]}
        rotation={[-0.07, -0.27, -0.87]}
        scale={[-0.02, -0.04, -0.02]}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials["Material.003"]}
        position={[-0.48, 0.63, 0.76]}
        rotation={[-0.03, 0.07, -0.17]}
        scale={[0.09, 0.09, 0.06]}
      />
    </group>
  );
}

useGLTF.preload("./gltf/cupcakeOne.glb");
