/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 gingerbread.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Gingerbread(props) {
  const { nodes, materials } = useGLTF("./gltf/gingerbread.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.GingerbreadMan.geometry}
        material={materials.Gingerbread}
      />
      <mesh
        geometry={nodes.GingerbreadTree.geometry}
        material={materials.Gingerbread}
      />
      <mesh
        geometry={nodes.Frosting_GingerbreadMan.geometry}
        material={materials.Gingerbread}
      />
      <mesh
        geometry={nodes.Frosting_GingerbreadTree.geometry}
        material={materials.Gingerbread}
      />
    </group>
  );
}

useGLTF.preload("./gltf/gingerbread.gltf");
