/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, ImageProps, TextProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type PoolListCom1024pxOverridesProps = {
    PoolListCom1024px?: PrimitiveOverrideProps<FlexProps>;
    Networks39913185?: PrimitiveOverrideProps<FlexProps>;
    "Networks List"?: PrimitiveOverrideProps<TextProps>;
    "NetWork List39913187"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 1939913188"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913189"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2039913190"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913191"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2139913192"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913193"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2239913194"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913195"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2339913196"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913197"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2439913198"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913199"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2539913200"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913201"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2639913202"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913203"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2739913204"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913205"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2839913206"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913207"?: PrimitiveOverrideProps<ImageProps>;
    Networks39913290?: PrimitiveOverrideProps<FlexProps>;
    "Dex List"?: PrimitiveOverrideProps<TextProps>;
    "NetWork List39913292"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 1939913293"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913294"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2039913295"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913296"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2139913297"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913298"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2239913299"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913300"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2339913301"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913302"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2439913303"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913304"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2539913305"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913306"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2639913307"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913308"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2739913309"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913310"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2839913311"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:em1OiomfG3g39913312"?: PrimitiveOverrideProps<ImageProps>;
    Top?: PrimitiveOverrideProps<FlexProps>;
    "Frame 37"?: PrimitiveOverrideProps<FlexProps>;
    "LP List"?: PrimitiveOverrideProps<TextProps>;
    "Frame 13"?: PrimitiveOverrideProps<FlexProps>;
    WALLET?: PrimitiveOverrideProps<TextProps>;
    "Frame 38"?: PrimitiveOverrideProps<FlexProps>;
    DEPOSITED?: PrimitiveOverrideProps<TextProps>;
    "Frame 39"?: PrimitiveOverrideProps<FlexProps>;
    APY?: PrimitiveOverrideProps<TextProps>;
    "Frame 14"?: PrimitiveOverrideProps<FlexProps>;
    TVL?: PrimitiveOverrideProps<TextProps>;
    "Frame 40"?: PrimitiveOverrideProps<FlexProps>;
    "DAILY RATE"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1539913034"?: PrimitiveOverrideProps<FlexProps>;
    Action?: PrimitiveOverrideProps<TextProps>;
    List?: PrimitiveOverrideProps<FlexProps>;
    "Frame 11"?: PrimitiveOverrideProps<FlexProps>;
    PoolImg?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:AYOloXgqjzo39913039"?: PrimitiveOverrideProps<ImageProps>;
    "unsplash:em1OiomfG3g39913040"?: PrimitiveOverrideProps<ImageProps>;
    LogoTitle?: PrimitiveOverrideProps<FlexProps>;
    "Overnight Pulse Act ll"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 9"?: PrimitiveOverrideProps<FlexProps>;
    VELOCIMETER?: PrimitiveOverrideProps<TextProps>;
    "Frame 8"?: PrimitiveOverrideProps<FlexProps>;
    "unsplash:AYOloXgqjzo39913047"?: PrimitiveOverrideProps<ImageProps>;
    "STADER BOOST"?: PrimitiveOverrideProps<TextProps>;
    "Frame 85"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 1539913049"?: PrimitiveOverrideProps<FlexProps>;
    "039913050"?: PrimitiveOverrideProps<TextProps>;
    "Frame 18"?: PrimitiveOverrideProps<FlexProps>;
    "039913052"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1939913053"?: PrimitiveOverrideProps<FlexProps>;
    "99.99%"?: PrimitiveOverrideProps<TextProps>;
    "Frame 16"?: PrimitiveOverrideProps<FlexProps>;
    "$999,99939913056"?: PrimitiveOverrideProps<TextProps>;
    "Frame 2039913057"?: PrimitiveOverrideProps<FlexProps>;
    "$999,99939913058"?: PrimitiveOverrideProps<TextProps>;
    "Frame 17"?: PrimitiveOverrideProps<FlexProps>;
    "Add Liquidity"?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type PoolListCom1024pxProps = React.PropsWithChildren<Partial<FlexProps> & {
    overrides?: PoolListCom1024pxOverridesProps | undefined | null;
}>;
export default function PoolListCom1024px(props: PoolListCom1024pxProps): React.ReactElement;
